name: Android CI Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Обновлено до v4

      - name: set up JDK 17
        uses: actions/setup-java@v4 # Обновлено до v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Если врапера (gradlew) нет, мы его создадим прямо в процессе
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build APK
        # Собираем модуль app, который лежит в core/app
        run: ./gradlew :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4 # Обновлено до v4 (решает твою ошибку!)
        with:
          name: FightGame_Final_Build
          path: core/app/build/outputs/apk/debug/app-debug.apk
          
